### ISSUE TITLE
Reloading a template in development

### ISSUE THREAD

**Issue by xiake999** [gowww/app#7]
make incremental changes to the template

**Comment by xiake999** [comment]
@arthurwhite  To reflect changes made in Static Files (js, css), view template file and Go Source Code without server restart.

**Comment by xthezealot** [comment]
That's why I've made the *gowww* command, not documented yet, but usable.
Download: `go get -u github.com/gowww/app/cmd/gowww`.

In your project directory, just run `gowww` or `gowww watch` to:
- recompile the project on Go code modification,
- rerun the server on template file (in the *views* directory) modification,
- recompile assets on modification (at the moment, it only supports `scripts/*.go` files with GopherJS and `styles/*.styl` files with Stylus).

The server must be restarted on template change because the templates are parsed and kept in memory. And actually, I don't want to integrate a file watcher directly to the server, just for development. It would just increase the binary size and it won't be much faster than a restart.
