### ISSUE TITLE
xss support

### ISSUE THREAD

**Issue by xiake999** [gowww/app#8]
removes (deletes) all HTML and malicious detected input from user input on

handles three Request types:
JSON requests - Content-Type application/json
Form Encoded - Content-Type application/x-www-form-urlencoded
Multipart Form Data - Content-Type multipart/form-data

@arthurwhite  Any plan support?

**Comment by xthezealot** [comment]
- With Go [html/template](https://golang.org/pkg/html/template/), action outputs (between `{{` and `}}`) are escaped by default.
- The `X-XSS-Protection` header is set to `1; mode=block` by default.

Do you have another approach of the problem?

**Comment by xiake999** [comment]
The XSS filtering is performed by HTML sanitizer [Bluemonday](https://github.com/microcosm-cc/bluemonday).
applied on http POST and PUT Requests only
That's how I realized it at the moment

**Comment by xthezealot** [comment]
It's pointless to sanitize an input if it will be escaped in the response.

Using [Bluemonday](https://github.com/microcosm-cc/bluemonday) is required when you expect your users to submit HTML (or Markdown) and you explicitly return it unescaped. But that's far from a common case.

So rather than wasting resources on sanitizing all inputs by default, it's effectively better to call [Bluemonday](https://github.com/microcosm-cc/bluemonday) only when needed.

**Comment by xiake999** [comment]
I see. Thank you
