### ISSUE TITLE
Is the project still under maintenance?

### ISSUE THREAD

**Issue by xserve98** [gowww/app#9]
Will it be maintained?

**Comment by xthezealot** [comment]
Personally, I'll be on Python for the next months so I'll slow down my Go contributions.
But you can still consider the [gowww](https://github.com/gowww) repositories as maintained: **critical issues (bugs) will be solved and pull requests considered ASAP**.

Finally, even if there are no automated tests for this package and its API changed a lot since the first commit, it's perfectly usable as is.
